### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ProgramistaZaDyszke** [Bassman2/UsbMonitor#8]
How to use this monitor?

**Comment by Bassman2** [comment]
Have a look at the demo apps (https://github.com/Bassman2/UsbMonitor/tree/master/Demo) and the documentation inside of the Nuget packages https://www.nuget.org/packages/FormsUsbMonitor/ and https://www.nuget.org/packages/WpfUsbMonitor/ .

**Comment by ProgramistaZaDyszke** [comment]
Error signing output with public key from file 'Bassman.snk' -- File not found.

**Comment by Bassman2** [comment]
Bassman.snk is my own signing key, which I can not commit for security reason. Create your own or deactivate signing.

**Comment by ProgramistaZaDyszke** [comment]
Ok so I opened .csproj with notepad then I edit  SignAssembly true SignAssembly to "false" and everything is working. Can be closed.

**Comment by Bassman2** [comment]
You can deactivate it in VS.
